language: node_js
node_js: node
script: gulp test
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    repo: ComplexCurves/ComplexCurves
    branch: master
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_879c97e4b04e_key -iv $encrypted_879c97e4b04e_iv -in github_deploy_key.enc -out github_deploy_key -d
  -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d
- npm install -g npm@^5.6.0
