language: node_js
node_js:
  - node
  - "0.12"
script: make test
deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      repo: kranich/ComplexCurves
      branch: master
    skip_cleanup: true
